apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task11-pv-claim
  namespace: idam
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: task11-pv-volume
